version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    command: >
      postgres -c wal_level=logical
               -c max_wal_senders=10
               -c max_replication_slots=10
    volumes:
      - ./sample_init.sql:/docker-entrypoint-initdb.d/sample_init.sql:ro
    networks:
      - cdc-network

  jobmanager:
    image: flink:1.20.1-scala_2.12-java8
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - FLINK_PROPERTIES=jobmanager.rpc.address: flink-jobmanager
    volumes:
      - ./flink-connectors:/opt/flink/lib
    networks:
      - cdc-network

  taskmanager:
    image: flink:1.20.1-scala_2.12-java8
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - FLINK_PROPERTIES=jobmanager.rpc.address: flink-jobmanager
    volumes:
      - ./flink-connectors:/opt/flink/lib
    networks:
      - cdc-network

networks:
  cdc-network:
    external: true
