version: '3.8'

services:
  starrocks-fe:
    image: starrocks/fe-ubuntu:3.2-latest
    container_name: starrocks-fe
    ports:
      - "8030:8030"   # HTTP port
      - "9010:9010"   # RPC port
      - "9020:9020"   # Query port
    environment:
      - FE_ROOT_DIR=/opt/starrocks/fe
    volumes:
      - ./starrocks/fe/meta:/opt/starrocks/fe/meta
      - ./starrocks/fe/log:/opt/starrocks/fe/log
    command: >
      bash -c "/opt/starrocks/fe/bin/start_fe.sh --daemon;
               tail -f /opt/starrocks/fe/log/fe.out"
    networks:
      - cdc-network

  starrocks-be:
    image: starrocks/be-ubuntu:3.2-latest
    container_name: starrocks-be
    ports:
      - "8040:8040"
    environment:
      - BE_ROOT_DIR=/opt/starrocks/be
    volumes:
      - ./starrocks/be/storage:/opt/starrocks/be/storage
      - ./starrocks/be/log:/opt/starrocks/be/log
    command: >
      bash -c "/opt/starrocks/be/bin/start_be.sh --daemon;
               tail -f /opt/starrocks/be/log/be.out"
    depends_on:
      - starrocks-fe
    networks:
      - cdc-network

networks:
  cdc-network:
    external: true

