services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    networks:
      - cdc-network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sample_init.sql:/docker-entrypoint-initdb.d/init.sql

  flink-jobmanager:
    image: flink:1.20.1-scala_2.12-java8
    container_name: flink-jobmanager
    command: jobmanager
    ports:
      - "8081:8081"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    volumes:
      - ./flink-connectors:/opt/flink/usrlib
    networks:
      - cdc-network

  flink-taskmanager:
    image: flink:1.20.1-scala_2.12-java8
    container_name: flink-taskmanager
    command: taskmanager
    depends_on:
      - flink-jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    volumes:
      - ./flink-connectors:/opt/flink/usrlib
    networks:
      - cdc-network

networks:
  cdc-network:
    external: true

volumes:
  pgdata:
