version: '3.8'
services:
  starrocks-fe:
    image: starrocks/fe-ubuntu:3.2-latest
    container_name: starrocks-fe
    hostname: starrocks-fe
    ports:
      - "8030:8030"
      - "9030:9030"
    networks:
      - cdc-network
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-h", "127.0.0.1", "-P9030", "-e", "SHOW FRONTENDS;"]
      interval: 10s
      timeout: 5s
      retries: 5

  starrocks-be:
    image: starrocks/be-ubuntu:3.2-latest
    container_name: starrocks-be
    hostname: starrocks-be
    depends_on:
      starrocks-fe:
        condition: service_healthy
    command: >
      bash -c "ulimit -n 65535;
               sleep 15;
               mysql --connect-timeout 2 -h starrocks-fe -P9030 -u root                  -e \"ALTER SYSTEM ADD BACKEND 'starrocks-be:9050';\";
               bash /opt/starrocks/be/bin/start_be.sh"
    networks:
      - cdc-network
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-h", "starrocks-fe", "-P9030", "-e", "SHOW BACKENDS;"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  cdc-network:
    external: true
